language: php
php: 7.4
dist: xenial

env:
  matrix:
    - TEST_GROUP=magento_23
matrix:
  exclude:
    - php: 7.4
      env: TEST_GROUP=magento_23

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update 1.10.16

cache:
  apt: true
  directories: $HOME/.composer/cache
install: ./travis/install.sh
before_script: ./travis/before_script.sh
script: phpunit -c $HOME/build/magento2ce/dev/tests/integration/phpunit.xml.dist --testsuite Integration
after_success: ./travis/after_success.sh
